comment:
  image:
    repository: mirror.gcr.io/wowan/comment
    tag: "3.0"
  service:
    externalPort: 9292

post:
  image:
    repository: mirror.gcr.io/wowan/post
    tag: "3.0"
  service:
    externalPort: 5000

ui:
  image:
    repository: mirror.gcr.io/wowan/ui
    tag: "3.0"
  service:
    externalPort: 9292
