---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "comment.fullname" . }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ template "comment.fullname" . }}
      port:
        number: 9292
  tls:
  - secretName: ui-ingress
